### ISSUE TITLE
将附件显示为图标无效

### ISSUE THREAD

**Issue by gee1k** [nusr/awesome-macos-command-line-zh#1]
将附件显示为图标无效

```
defaults write com.apple.mail DisableInlineAttachmentViewing -bool yes
```

没有改变

**Comment by nusr** [comment]
这个功能应该是邮箱添加附件，文本显示为图标，而不是显示文件内容。
<img width="767" alt="屏幕快照 2019-05-01 下午9 09 51" src="https://user-images.githubusercontent.com/12200340/57018348-c2ef6680-6c55-11e9-87a7-55c61dd3d98e.png">
我没设置这个功能，默认显示为图标。我的mac版本是 10.14.4，邮箱是 12.4
这个应该和版本有关系。

**Comment by gee1k** [comment]
你添加图片试试

**Comment by nusr** [comment]
@gee1k  确实没效。右键可以转换为图标，或者更换右键客户端。
